# Copyright 2026 Observational Health Data Sciences and Informatics
#
# This file is part of Keeper
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create a sensitive cohort
#' 
#' @description
#' Creates a cohort that is highly sensitive. Nobody outside the cohort is expected to have the disease. As a 
#' consequence, specificity inside the cohort is likely low.
#' 
#' This cohort can be used to determine the sensitivity of a cohort definition.
#' 
#' @template Connection
#' 
#' @template CdmDatabaseSchema
#'
#' @template TempEmulationSchema
#' 
#' @template CohortTable
#'
#' @param cohortDefinitionId         The cohort definition ID that will be used for the cohort.
#' @param sampleSize                 The maximum number of persons to sample from the cohort.
#' @param personIds                  Only persons with these IDs will be selected. Can be a vector of numeric or string
#'                                   (to avoid integer overflows).
#' @param keeperConceptSets          A data frame with Keeper concept sets as generated by 
#'                                   [generateKeeperConceptSets()].
#' @param phenotypeName              (Optional) Name of the phenotype. Will be included in the output.
#' @param useDescendants             Include the  descendants of the concepts specified in the `keeperConceptSets`, or 
#'                                   use only the verbatim concepts?
#' @param removePersonId             Remove person IDs from the output? Can be set to `TRUE` for privacy reasons.                                
#'        
#' @returns 
#' Returns a list of tibbles with data in the various KEEPER categories.
#'                                   
#' @export
generateKeeper <- function(connectionDetails = NULL,
                           connection = NULL,
                           cdmDatabaseSchema,
                           tempEmulationSchema = getOption("sqlRenderTempEmulationSchema"),
                           cohortDatabaseSchema,
                           cohortTable,
                           cohortDefinitionId,
                           sampleSize = 20,
                           personIds = NULL,
                           keeperConceptSets,
                           phenotypeName = NULL,
                           useDescendants = TRUE,
                           removePersonId = FALSE) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertClass(connectionDetails, "ConnectionDetails", null.ok = TRUE, add = errorMessages)
  checkmate::assertClass(connection, "DatabaseConnectorConnection", null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cdmDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(tempEmulationSchema, len = 1, null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(cohortTable, len = 1, add = errorMessages)
  checkmate::assertIntegerish(cohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertIntegerish(sampleSize, len = 1, lower = 1, add = errorMessages)
  if (is.character(personIds)) {
    checkmate::assertCharacter(personIds, min.len = 1, add = errorMessages)
  } else {
    checkmate::assertIntegerish(personIds, min.len = 1, null.ok = TRUE, add = errorMessages)
  }
  checkmate::assertDataFrame(keeperConceptSets, min.rows = 1, add = errorMessages)
  checkmate::assertNames(colnames(keeperConceptSets), must.include = c("conceptId",
                                                                       "conceptName", 
                                                                       "vocabularyId",
                                                                       "conceptSetName",
                                                                       "target"), add = errorMessages)
  checkmate::assertCharacter(phenotypeName, len = 1, add = errorMessages)
  checkmate::assertLogical(useDescendants, len = 1, add = errorMessages)
  checkmate::assertLogical(removePersonId, len = 1, add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  if (is.null(connectionDetails) && is.null(connection)) {
    stop("Must provide either connectionDetails or a connection.")
  }
  
  cohortTableIsTemp <- FALSE
  if (is.null(cohortDatabaseSchema)) {
    if (grepl(
      pattern = "#",
      x = cohortTable,
      fixed = TRUE
    )) {
      cohortTableIsTemp <- TRUE
    } else {
      stop("cohortDatabaseSchema is NULL, but cohortTable is not temporary.")
    }
  }
  usePersonIds <- !is.null(personIds)
  
  startTime <- Sys.time()
  
  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }
  
  message("Uploading concept sets")
  conceptSets <- keeperConceptSets |>
    mutate(target = if_else(.data$target == "Disease of interest", 1, 0))
  DatabaseConnector::insertTable(
    connection = connection,
    tableName = "#concept_sets",
    data = conceptSets,
    dropTableIfExists = TRUE,
    createTable = TRUE,
    tempTable = TRUE,
    camelCaseToSnakeCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )
  
  if (usePersonIds) {
    message("Uploading person IDs")
    DatabaseConnector::insertTable(
      connection = connection,
      tableName = "#person_ids",
      data = tibble(person_id = personIds),
      dropTableIfExists = TRUE,
      createTable = TRUE,
      tempTable = TRUE,
      tempEmulationSchema = tempEmulationSchema
    )
  }
  
  message("Identifying KEEPER cohort")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "CreateKeeperCohort.sql", 
    packageName = "Keeper", 
    dbms = DatabaseConnector::dbms(connection),
    use_person_ids = usePersonIds,
    sample_size = sampleSize,
    cohort_table = if (cohortTableIsTemp) cohortTable else paste(cohortDatabaseSchema, cohortTable, sep = "."),
    cohort_definition_id = cohortDefinitionId,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)
  
  message("Constructing KEEPER profiles")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "Keeper.sql", 
    packageName = "Keeper", 
    dbms = DatabaseConnector::dbms(connection),
    cdm_database_schema = cdmDatabaseSchema,
    use_descendants = useDescendants,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)
  
  keeperTables <- c("demographics",
                    "presentation",
                    "visit_context",
                    "symptoms",
                    "prior_disease",
                    "post_disease",
                    "prior_drugs",
                    "post_drugs",
                    "prior_treatment_procedures",
                    "post_treatment_procedures",
                    "alternative_diagnoses",
                    "diagnostic_procedures",
                    "measurements",
                    "death")
  
  message("Downloading KEEPER profiles")
  sql <- "SELECT * FROM #@table;"
  keeper <- list()
  for (keeperTable in keeperTables) {
    table <- DatabaseConnector::renderTranslateQuerySql(
      connection = connection,
      sql = sql,
      table = keeperTable,
      snakeCaseToCamelCase = TRUE,
      tempEmulationSchema = tempEmulationSchema
    ) |>
      as_tibble()
    table <- table |>
      mutate(target = case_when(
        .data$target == 2 ~ "Both",
        .data$target == 1 ~ "Disease of interest",
        .data$target == 0 ~ "Alternative diagnoses",
        TRUE ~ "Other"
      ))
    if (keeperTable == "demographics") {
      table <- tibble(
        generatedId = rep(table$generatedId, 6),
        startDay = c(rep(0, nrow(table)),
                     rep(0, nrow(table)),
                     rep(0, nrow(table)),
                     table$observationStartDay,
                     rep(0, nrow(table)),
                     rep(0, nrow(table))),
        endDay = c(rep(0, nrow(table)),
                   rep(0, nrow(table)),
                   rep(0, nrow(table)),
                   table$observationEndDay,
                   rep(0, nrow(table)),
                   rep(0, nrow(table))),                     
        conceptId = c(rep(NA, nrow(table)),
                      rep(NA, nrow(table)), 
                      table$genderConceptId, 
                      rep(NA, nrow(table)),
                      table$raceConceptId,
                      table$ethnicityConceptId),
        conceptName = c(table$personId, 
                        as.character(table$age), 
                        table$genderConceptName,
                        rep("Observation period", nrow(table)),
                        table$raceConceptName,
                        table$ethnicityConceptName), 
        category = c(rep("personId", nrow(table)), 
                     rep("age", nrow(table)),
                     rep("sex", nrow(table)),
                     rep("observationPeriod", nrow(table)),
                     rep("race", nrow(table)),
                     rep("ethnicity", nrow(table))),
        target = rep(table$target, 6)
      ) 
      if (removePersonId) {
        table <- table |>
          filter(.data$category != "personId")
      }
    } else {
      table <- table |>
        mutate(category = SqlRender::snakeCaseToCamelCase(keeperTable))
    }
    keeper[[length(keeper) + 1]] <- table
  }
  keeper <- bind_rows(keeper)
  
  message("Downloading meta-data")
  sql <- "SELECT cdm_source_name, cdm_source_abbreviation, cdm_release_date FROM @cdm_database_schema.cdm_source;"
  metaData <- DatabaseConnector::renderTranslateQuerySql(
    connection = connection,
    sql = sql,
    cdm_database_schema = cdmDatabaseSchema,
    snakeCaseToCamelCase = TRUE
  )
  if (nrow(metaData) == 0) {
    stop("The cdm_source table is not populated but is required.")
  }
  metaData <- tibble(
    generatedId = unique(keeper$generatedId)
  ) |>
    cross_join(
      tibble(
        startDay = 0,
        conceptId = c(NA,
                      NA,
                      NA,
                      cohortDefinitionId),
        conceptName = c(metaData$cdmSourceName[1], 
                        metaData$cdmSourceAbbreviation[1],
                        as.character(metaData$cdmReleaseDate[1]),
                        if (is.null(phenotypeName)) "" else phenotypeName),
        category = c("cdmSourceName",
                     "cdmSourceAbbreviation",
                     "cdmReleaseDate",
                     "phenotype")
      )
    )
  keeper <- bind_rows(keeper, metaData)
  
  message("Removing temp tables")
  toDelete <- c("concept_sets", 
                "full_concept_sets",
                "cohort",
                keeperTables)
  if (usePersonIds) {
    toDelete <- c(toDelete, "person_ids")
  }
  sql <- paste(sprintf("TRUNCATE TABLE #%s; DROP TABLE #%s;", toDelete, toDelete), collapse = "\n")  
  DatabaseConnector::renderTranslateExecuteSql(
    connection = connection, 
    sql = sql,
    tempEmulationSchema = tempEmulationSchema
  )
  
  delta <- Sys.time() - startTime
  message(paste0("Generating KEEPER profiles took ",
                 round(delta,1), 
                 " ",
                 attr(delta, "units"),
                 ". Cohort size is ",
                 format(length(unique(keeper$generatedId)), scientific = FALSE, big.mark = ","),
                 " persons."))
  return(keeper)
}


#' Covert KEEPER profiles to a table
#'
#' @param keeper         KEEPER profiles as created using the [generateKeeper()] function.
#' @param removePersonId Remove person IDs from the output? Can be set to `TRUE` for privacy reasons.  
#'
#' @returns
#' A tibble with one row per person, and text columns for each KEEPER category. Can be used for manual review.
#' 
#' @export
convertKeeperToTable <- function(keeper, removePersonId = FALSE) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertDataFrame(keeper, add = errorMessages)
  checkmate::assertNames(colnames(keeper), must.include = c("generatedId",
                                                            "startDay", 
                                                            "endDay",
                                                            "conceptId",
                                                            "conceptName",
                                                            "category",
                                                            "target",
                                                            "extraData"), add = errorMessages)
  checkmate::assertLogical(removePersonId, len = 1, add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  
  age <- keeper |>
    filter(.data$category == "age") |>
    transmute(.data$generatedId,
              age = .data$conceptName)
  sex <- keeper |>
    filter(.data$category == "sex") |>
    transmute(.data$generatedId,
              sex = .data$conceptName)
  observationPeriod <- keeper |>
    filter(.data$category == "observationPeriod") |>
    transmute(.data$generatedId,
              observationPeriod = sprintf("%d days - %s days", .data$startDay, .data$endDay))
  race <- keeper |>
    filter(.data$category == "race") |>
    transmute(.data$generatedId,
              race = .data$conceptName)
  ethnicity <- keeper |>
    filter(.data$category == "ethnicity") |>
    transmute(.data$generatedId,
              ethnicity = .data$conceptName)
  output <- age |>
    inner_join(sex, by = join_by("generatedId")) |>
    inner_join(observationPeriod, by = join_by("generatedId")) |>
    inner_join(race, by = join_by("generatedId")) |>
    inner_join(ethnicity, by = join_by("generatedId")) 
  
  keeperTables <- c("presentation",
                    "visitContext",
                    "symptoms",
                    "priorDisease",
                    "postDisease",
                    "priorDrugs",
                    "postDrugs",
                    "priorTreatmentProcedures",
                    "postTreatmentProcedures",
                    "alternativeDiagnoses",
                    "diagnosticProcedures",
                    "measurements",
                    "death")
  
  generateLabel <- function(conceptName, startDay, endDay, extraData, keeperTable) {
    if (keeperTable == "presentation") {
      return(paste0(conceptName, if_else(extraData == "",  "", sprintf(" (%s)", extraData))))
    } else if (keeperTable == "visitContext") {
      return(sprintf("%s%s%s",
                     conceptName,
                     if_else(extraData == "", "", sprintf(" - %s", extraData)),
                     if_else(startDay == endDay, "",  sprintf(" (%d days)", endDay - startDay))))
    } else if (keeperTable %in% c("priorDrugs", "postDrugs")) {
      return(sprintf("%s (day %s)", 
                     conceptName[1],
                     paste(sprintf("%d for %d day%s", 
                                   startDay, 
                                   endDay - startDay + 1,
                                   if_else(endDay == startDay, "", "s")),
                           collapse = ", ")))
    } else if (keeperTable == "measurements") {
      return(sprintf("%s (day %s)", 
                     conceptName[1],
                     paste(if_else(extraData == "",
                                   as.character(startDay),
                                   sprintf("%d with value %s", startDay, extraData)),
                           collapse = ", ")))     
    } else {
      return(sprintf("%s (day %s)", 
                     conceptName[1],
                     paste(startDay, collapse = ", ")))     
    }
  }

  for (keeperTable in keeperTables) {
    table <- keeper |>
      filter(.data$category == keeperTable) |>
      mutate(
        sortOrder = case_when(
        .data$target == "Disease of interest" ~ 2,
        .data$target == "Both" ~ 1,
        .data$target == "Alternative diagnoses" ~ 0,
        TRUE ~ -1),
        extraGroup = if (keeperTable == "presentation") .data$extraData else "") |>
      group_by(.data$generatedId, .data$conceptName, .data$sortOrder, .data$extraGroup) |>
      arrange(.data$startDay) |>
      summarise(label = generateLabel(.data$conceptName, .data$startDay, .data$endDay, .data$extraData, keeperTable), .groups = "drop") |>
      group_by(.data$generatedId) |>
      arrange(desc(.data$sortOrder), .data$label) |>
      summarise(label = paste(.data$label, collapse = "; "))
    colnames(table)[2] <- keeperTable
    output <- output |>
      left_join(table, by = join_by("generatedId"))
    
  }
  
  # Replace all NA with "":
  output <- output %>% 
    mutate(across(-matches("generatedId"), ~ coalesce(as.character(.), "")))
  
  if ("phenotype" %in% keeper$category) {
    output <- keeper |>
      filter(.data$category == "phenotype") |>
      transmute(.data$generatedId,
                phenotype = .data$conceptName) |>
      inner_join(output, by = join_by("generatedId"))
  }
  
  if (!removePersonId && "personId" %in% keeper$category) {
    output <- keeper |>
      filter(.data$category =="personId") |>
      select("generatedId", personId = "conceptName") |>
      inner_join(output, by = join_by("generatedId"))
  }
  
  return(output)
}
