# Copyright 2026 Observational Health Data Sciences and Informatics
#
# This file is part of Keeper
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create a sensitive cohort
#' 
#' @description
#' Creates a cohort that is highly sensitive. Nobody outside the cohort is expected to have the disease. As a 
#' consequence, specificity inside the cohort is likely low.
#' 
#' This cohort can be used to determine the sensitivity of a cohort definition.
#' 
#' @template Connection
#' 
#' @template CdmDatabaseSchema
#'
#' @template TempEmulationSchema
#' 
#' @template CohortTable
#' 
#' @param createCohortTable          Create the cohort table. If `TRUE` and the table already exists it will first be 
#'                                   deleted.
#' @param cohortDefinitionId         The cohort definition ID that will be used for the cohort.
#' @param keeperConceptSets          A data frame with Keeper concept sets as generated by 
#'                                   [generateKeeperConceptSets()].
#' @param useDescendants             Include the  descendants of the concepts specified in the `keeperConceptSets`, or 
#'                                   use only the verbatim concepts?
#' @param removePersonId             Remove person IDs from the output? Can be set to `TRUE` for privacy reasons.                                
#'        
#' @returns 
#' Returns a list of tibbles with data in the various KEEPER categories.
#'                                   
#' @export
generateKeeper <- function(connectionDetails = NULL,
                           connection = NULL,
                           cdmDatabaseSchema,
                           tempEmulationSchema = getOption("sqlRenderTempEmulationSchema"),
                           cohortDatabaseSchema,
                           cohortTable,
                           cohortDefinitionId,
                           sampleSize = 20,
                           personIds = NULL,
                           keeperConceptSets,
                           useDescendants = TRUE,
                           removePersonId = FALSE) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertClass(connectionDetails, "ConnectionDetails", null.ok = TRUE, add = errorMessages)
  checkmate::assertClass(connection, "DatabaseConnectorConnection", null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cdmDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(tempEmulationSchema, len = 1, null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(cohortTable, len = 1, add = errorMessages)
  checkmate::assertIntegerish(cohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertDataFrame(keeperConceptSets, min.rows = 1, add = errorMessages)
  checkmate::assertNames(colnames(keeperConceptSets), must.include = c("conceptId",
                                                                       "conceptName", 
                                                                       "vocabularyId",
                                                                       "conceptSetName",
                                                                       "target"), add = errorMessages)
  checkmate::assertLogical(useDescendants, len = 1, add = errorMessages)
  checkmate::assertLogical(removePersonId, len = 1, add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  if (is.null(connectionDetails) && is.null(connection)) {
    stop("Must provide either connectionDetails or a connection.")
  }
  
  cohortTableIsTemp <- FALSE
  if (is.null(cohortDatabaseSchema)) {
    if (grepl(
      pattern = "#",
      x = cohortTable,
      fixed = TRUE
    )) {
      cohortTableIsTemp <- TRUE
    } else {
      stop("cohortDatabaseSchema is NULL, but cohortTable is not temporary.")
    }
  }
  usePersonIds <- !is.null(personIds)
  
  startTime <- Sys.time()
  
  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }
  
  message("Uploading concept sets")
  conceptSets <- keeperConceptSets |>
    mutate(target = if_else(.data$target == "Disease of interest", 1, 0))
  DatabaseConnector::insertTable(
    connection = connection,
    tableName = "#concept_sets",
    data = conceptSets,
    dropTableIfExists = TRUE,
    createTable = TRUE,
    tempTable = TRUE,
    camelCaseToSnakeCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )
  
  if (usePersonIds) {
    message("Uploading person IDs")
    DatabaseConnector::insertTable(
      connection = connection,
      tableName = "#person_ids",
      data = tibble(person_id = personIds),
      dropTableIfExists = TRUE,
      createTable = TRUE,
      tempTable = TRUE,
      tempEmulationSchema = tempEmulationSchema
    )
  }
  
  message("Identifying KEEPER cohort")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "CreateKeeperCohort.sql", 
    packageName = "Keeper", 
    dbms = DatabaseConnector::dbms(connection),
    use_person_ids = usePersonIds,
    sample_size = sampleSize,
    cohort_table = if (cohortTableIsTemp) cohortTable else paste(cohortDatabaseSchema, cohortTable, sep = "."),
    cohort_definition_id = cohortDefinitionId,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)
  
  message("Constructing KEEPER profiles")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "Keeper.sql", 
    packageName = "Keeper", 
    dbms = DatabaseConnector::dbms(connection),
    cdm_database_schema = cdmDatabaseSchema,
    use_descendants = useDescendants,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)
  
  keeperTables <- c("demographics",
                    "presentation",
                    "visit",
                    "symptoms",
                    "prior_disease",
                    "post_disease",
                    "prior_drugs",
                    "post_drugs",
                    "prior_treatment_procedures",
                    "post_treatment_procedures",
                    "alternative_diagnoses",
                    "diagnostic_procedures",
                    "measurements",
                    "death")
  
  message("Downloading KEEPER profiles")
  sql <- "SELECT * FROM #@table;"
  keeper <- list()
  for (keeperTable in keeperTables) {
    table <- DatabaseConnector::renderTranslateQuerySql(
      connection = connection,
      sql = sql,
      table = keeperTable,
      snakeCaseToCamelCase = TRUE,
      tempEmulationSchema = tempEmulationSchema
    ) |>
      as_tibble()
    if ("target" %in% colnames(table)) {
      table <- table |>
        mutate(target = case_when(
          .data$target == 1 ~ "Disease of interest",
          .data$target == 0 ~ "Alternative diagnoses",
          TRUE ~ "Other"
        ))
    }
    keeper[[SqlRender::snakeCaseToCamelCase(keeperTable)]] <- table
  }

  if (removePersonId) {
    keeper[["demographics"]]$personId <- NULL
  }
  
  message("Removing temp tables")
  toDelete <- c("concept_sets", 
                "full_concept_sets",
                "cohort",
                keeperTables)
  if (usePersonIds) {
    toDelete <- c(toDelete, "person_ids")
  }
  sql <- paste(sprintf("TRUNCATE TABLE #%s; DROP TABLE #%s;", toDelete, toDelete), collapse = "\n")  
  DatabaseConnector::renderTranslateExecuteSql(
    connection = connection, 
    sql = sql,
    tempEmulationSchema = tempEmulationSchema
  )
  
  delta <- Sys.time() - startTime
  message(paste0("Generating KEEPER profiles took ",
                 round(delta,1), 
                 " ",
                 attr(delta, "units"),
                 ". Cohort size is ",
                 format(nrow(keeper[["demographics"]]), scientific = FALSE, big.mark = ","),
                 " persons."))
  return(keeper)
}


#' Covert KEEPER profiles to a table
#'
#' @param keeper         KEEPER profiles as created using the [generateKeeper()] function.
#' @param removePersonId Remove person IDs from the output? Can be set to `TRUE` for privacy reasons.  
#'
#' @returns
#' A tibble with one row per person, and text columns for each KEEPER category. Can be used for manual review.
#' 
#' @export
convertKeeperToTable <- function(keeper, removePersonId = FALSE) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertList(keeper, add = errorMessages)
  checkmate::assertNames(names(keeper), must.include = c("demographics",
                                                         "presentation", 
                                                         "visit",
                                                         "symptoms",
                                                         "priorDisease",
                                                         "postDisease",
                                                         "priorDrugs",
                                                         "postDrugs",
                                                         "priorTreatmentProcedures",
                                                         "postTreatmentProcedures",
                                                         "alternativeDiagnoses",
                                                         "diagnosticProcedures",
                                                         "measurements",
                                                         "death"), add = errorMessages)
  checkmate::assertLogical(removePersonId, len = 1, add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  
  if (!"personId" %in% keeper$demographics) {
    keeper$demographics <- keeper$demographics |>
      mutate(personId = .data$generatedId)
    removePersonId <- TRUE
  }
  demographics <- keeper$demographics |>
    transmute(
      .data$generatedId,
      .data$personId,
      .data$age,
      gender = .data$sex,
      observationPeriod = sprintf("%d days - %d days", .data$observationStartDay, .data$observationEndDay)
    )
  visitContext <- keeper$visit |>
    transmute(
      .data$generatedId,
      visitContext = paste0(.data$conceptName, 
                            if_else(.data$visitStartDay == .data$visitEndDay, 
                                    "", 
                                    sprintf(" (%d days)", .data$visitEndDay - .data$visitStartDay)))
    )

  presentation <- keeper$presentation |>
    mutate(
      label = paste0(.data$conceptName,
                     if_else(.data$metaData == "",
                             "",
                             sprintf(" (%s)", .data$metaData))
      ),
      target = case_when(
        .data$target == "Disease of interest" ~ 1,
        .data$target == "Alternative diagnoses" ~ 0,
        TRUE ~ -1
      )
    ) |>
    arrange(desc(.data$target), .data$label) |>
    group_by(.data$generatedId) |>
    summarise(presentation = paste(.data$label, collapse = "; "))
  
  symptoms <- keeper$symptoms |>
    group_by(.data$generatedId, .data$conceptName, .data$target) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$startDay, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(desc(.data$target), .data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(symptoms = paste(.data$label, collapse = "; "))
  
  priorDisease <- keeper$priorDisease |>
    group_by(.data$generatedId, .data$conceptName, .data$target) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$startDay, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(desc(.data$target), .data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(priorDisease = paste(.data$label, collapse = "; "))
  
  priorDrugs <- keeper$priorDrugs |>
    mutate(label = sprintf("%d for %d day%s", 
                           .data$startDay, 
                           .data$endDay - .data$startDay + 1,
                           if_else(.data$endDay == .data$startDay, "", "s"))) |>
    group_by(.data$generatedId, .data$conceptName, .data$target) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$label, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(desc(.data$target), .data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(priorDrugs = paste(.data$label, collapse = "; "))
  
  priorTreatmentProcedures <- keeper$priorTreatmentProcedures |>
    group_by(.data$generatedId, .data$conceptName, .data$target) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$startDay, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(desc(.data$target), .data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(priorTreatmentProcedures = paste(.data$label, collapse = "; "))
  
  diagnosticProcedures <- keeper$diagnosticProcedures |>
    group_by(.data$generatedId, .data$conceptName, .data$target) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$startDay, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(desc(.data$target), .data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(diagnosticProcedures = paste(.data$label, collapse = "; "))
  
  measurements <- keeper$measurements |>
    mutate(label = if_else(.data$measurementValue == "",
                           as.character(.data$startDay),
                           sprintf("%d with value %s", .data$startDay, .data$measurementValue))) |>
    group_by(.data$generatedId, .data$conceptName, .data$target) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$label, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(desc(.data$target), .data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(measurements = paste(.data$label, collapse = "; ")) 
  
  alternativeDiagnoses <- keeper$alternativeDiagnoses |>
    group_by(.data$generatedId, .data$conceptName) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$startDay, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(.data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(alternativeDiagnoses = paste(.data$label, collapse = "; "))
  
  postDisease <- keeper$postDisease |>
    group_by(.data$generatedId, .data$conceptName, .data$target) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$startDay, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(desc(.data$target), .data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(postDisease = paste(.data$label, collapse = "; "))
  
  postTreatmentProcedures <- keeper$postTreatmentProcedures |>
    group_by(.data$generatedId, .data$conceptName, .data$target) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$startDay, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(desc(.data$target), .data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(postTreatmentProcedures = paste(.data$label, collapse = "; "))
  
  postDrugs <- keeper$postDrugs |>
    mutate(label = sprintf("%d for %d day%s", 
                           .data$startDay, 
                           .data$endDay - .data$startDay + 1,
                           if_else(.data$endDay == .data$startDay, "", "s"))) |>
    group_by(.data$generatedId, .data$conceptName, .data$target) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$label, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(desc(.data$target), .data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(postDrugs = paste(.data$label, collapse = "; "))
  
  death <- keeper$death |>
    group_by(.data$generatedId, .data$conceptName) |>
    arrange(.data$startDay) |>
    summarise(days = paste(.data$startDay, collapse = ", "), .groups = "drop") |>
    mutate(label = sprintf("%s (day %s)", .data$conceptName, .data$days)) |>
    arrange(.data$conceptName) |>
    group_by(.data$generatedId) |>
    summarise(death = paste(.data$label, collapse = "; "))
  
  table <- demographics |>
    left_join(visitContext, join_by("generatedId")) |>
    left_join(presentation, join_by("generatedId")) |>
    left_join(symptoms, join_by("generatedId")) |>
    left_join(priorDisease, join_by("generatedId")) |>
    left_join(priorDrugs, join_by("generatedId")) |>
    left_join(priorTreatmentProcedures, join_by("generatedId")) |>
    left_join(diagnosticProcedures, join_by("generatedId")) |>
    left_join(measurements, join_by("generatedId")) |>
    left_join(alternativeDiagnoses, join_by("generatedId")) |>
    left_join(postDisease, join_by("generatedId")) |>
    left_join(postTreatmentProcedures, join_by("generatedId")) |>
    left_join(postDrugs, join_by("generatedId")) |>
    left_join(death, join_by("generatedId"))
  
  # Replace all NA with "":
  table <- table %>% 
    mutate(across(everything(), ~ coalesce(as.character(.), "")))
  
  if (removePersonId) {
    table$personId <- NULL
  }
  
  return(table)
}
