# Copyright 2024 Observational Health Data Sciences and Informatics
#
# This file is part of Keeper
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Parse the response of a LLM
#'
#' @param response          The response of a LLM to the system prompt with prompt generated by
#'                          `createSystemPrompt()` and `createPrompt()`, respectively.
#' @param noMatchIsDontKnow If the response doesn't fit any predefined pattern, should we return
#'                          "I don't know"?
#'
#' @return
#' Returns a character string with one of the following values:
#'
#' - "yes": Yes, the patient has the disease.
#' - "no": No, the patient does not have the disease.
#' - "I don't know": The LLM cannot decide whether the patient has the disease.
#' - NA: There was a problem parsing the LLM's response.
#'
#' @examples
#' parseLlmResponse("Summary: yes")
#' parseLlmResponse("Summary: It is unclear whether the patient has the disease.")
#'
#' @export
parseLlmResponse <- function(response, noMatchIsDontKnow = TRUE) {
  response <- paste(response, collapse = "\n")
  response <- trimws(gsub("^.*\nSummary:", "", response))
  response <- gsub("\\(Only \"yes\" or \"no\"\\)", "", response)
  if (grepl("500 Internal Server Error", response, ignore.case = TRUE)) {
    result <- NA
  } else if (grepl("\"yes\" or \"no\"", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("\"yes\\.?\"", response, ignore.case = TRUE)) {
    result <- "yes"
  } else if (grepl("\"no\\.?\"", response, ignore.case = TRUE)) {
    result <- "no"
  } else if (grepl("It is not the most probable scenario", response, ignore.case = TRUE)) {
    result <- "no"
  } else if (grepl("(^|2[\\. ]+|\\()no([^y-z]|$)", response, ignore.case = TRUE)) {
    result <- "no"
  } else if (grepl("\"don't know\\.?\"", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("\"unclear\\.?\"", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("\"uncertain\\.?\"", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("don't know", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("\"maybe\"", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("([^a-z]|^)yes([^a-z]|$)", response, ignore.case = TRUE)) {
    result <- "yes"
  } else if (grepl("([^a-z]|^)no([^a-z]|$)", response, ignore.case = TRUE)) {
    result <- "no"
  } else if (grepl("the evidence supports the diagnosis of", response, ignore.case = TRUE)) {
    result <- "yes"
  } else if (grepl("finding is inconclusive", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("further information is needed", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("I cannot[a-z ]+determine ", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("insufficient information", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("insufficient evidence", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("unclear", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("inconclusive", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("uncertain", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("definitive", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("possible", response, ignore.case = TRUE)) {
    result <- "I don't know"
  } else if (grepl("[^a-z]likely ", response, ignore.case = TRUE)) {
    result <- "yes"
  } else if (grepl("[^a-z]probable ", response, ignore.case = TRUE)) {
    result <- "yes"
  } else if (noMatchIsDontKnow) {
    result <- "I don't know"
  } else {
    result <- NA
    warning("Unable to parse response")
  }
  return(result)
}
