# Copyright 2025 Observational Health Data Sciences and Informatics
#
# This file is part of Keeper
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Parse the response of a LLM
#'
#' @param response          The response of a LLM to the system prompt with prompt generated by
#'                          `createSystemPrompt()` and `createPrompt()`, respectively.
#' @param noMatchIsInsufficientInformation If the response doesn't fit any predefined pattern, should we return
#'                          "I don't know"?
#'
#' @return
#' Returns a character string with one of the following values:
#'
#' - "yes": Yes, the patient has the disease.
#' - "no": No, the patient does not have the disease.
#' - "insufficient information": The LLM cannot decide whether the patient has the disease.
#' - NA: There was a problem parsing the LLM's response.
#'
#' @examples
#' parseLlmResponse("{\"verdict:\": \"Yes\"}")
#'
#' @export
parseLlmResponse <- function(response, noMatchIsInsufficientInformation = TRUE) {
  jsonPart <- sub('.*?(\\{.*\\}).*', '\\1', gsub(".*</think>", "", response))
  jsonPart <- gsub("[\r\n]", " ", jsonPart)
  parsed <- jsonlite::fromJSON(jsonPart)
  if (tolower(parsed$verdict) == "no") {
    isCase <- "no"
  } else if (tolower(parsed$verdict) == "yes") {
    isCase <- "yes"
  } else if (tolower(parsed$verdict) == "insufficient information") {
    isCase <- "insufficient information"
  } else if (noMatchIsInsufficientInformation) {
    isCase <- "insufficient information"
  } else {
    isCase <- NA
    warning("Unable to parse response: ", response)
  }
  if (isCase == "yes") {
    indexDay = parsed$`day of onset`
  } else {
    indexDay = NA
  }
  return(tibble(isCase = isCase, indexDay = indexDay))
}
