# Copyright 2026 Observational Health Data Sciences and Informatics
#
# This file is part of Keeper
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create a highly-sensitive cohort for a phenotype
#'
#' @description
#' Creates a cohort that is highly sensitive. Nobody outside the cohort is expected to have the disease. As a
#' consequence, specificity inside the cohort is likely low.
#'
#' This cohort can be used to determine the sensitivity of a cohort definition.
#'
#' The cohort is constructed by combining two sets:
#'
#' 1. Anybody who has one of the condition concepts of the disease of interest, indexed on the first occurrence.
#' 
#' 2. Anybody who has 'highly specific concepts' from at least two Keeper categories (symptoms, drugs, etc.), indexed 
#' on the first occurrence.
#' 
#' Highly specific concepts are concepts where at least 10% of those who have that concept also have a condition concept 
#' for the disease of interest. 
#'
#' @template Connection
#'
#' @template CdmDatabaseSchema
#'
#' @template TempEmulationSchema
#'
#' @param cohortDatabaseSchema       The name of the database schema that is the location where the
#'                                   cohort will be stored.
#' @param cohortTable                The table name where the cohort will be stored.
#' @param createCohortTable          Create the cohort table. If `TRUE` and the table already exists it will first be
#'                                   deleted.
#' @param cohortDefinitionId         The cohort definition ID that will be used for the cohort.
#' @param keeperConceptSets          A data frame with Keeper concept sets as generated by
#'                                   [generateKeeperConceptSets()].
#'
#' @returns
#' This function is primarily executed for instantiating the cohort in the cohort table. It does return a data frame
#' listing the concepts that were used to create the cohort.
#'
#' @export
createSensitiveCohort <- function(connectionDetails = NULL,
                                  connection = NULL,
                                  cdmDatabaseSchema,
                                  tempEmulationSchema = getOption("sqlRenderTempEmulationSchema"),
                                  cohortDatabaseSchema,
                                  cohortTable,
                                  createCohortTable = FALSE,
                                  cohortDefinitionId,
                                  keeperConceptSets) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertClass(connectionDetails, "ConnectionDetails", null.ok = TRUE, add = errorMessages)
  checkmate::assertClass(connection, "DatabaseConnectorConnection", null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cdmDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(tempEmulationSchema, len = 1, null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(cohortTable, len = 1, add = errorMessages)
  checkmate::assertLogical(createCohortTable, len = 1, add = errorMessages)
  checkmate::assertIntegerish(cohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertDataFrame(keeperConceptSets, min.rows = 1, add = errorMessages)
  checkmate::assertNames(colnames(keeperConceptSets), must.include = c(
    "conceptId",
    "conceptName",
    "vocabularyId",
    "conceptSetName",
    "target"
  ), add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  if (is.null(connectionDetails) && is.null(connection)) {
    stop("Must provide either connectionDetails or a connection.")
  }

  startTime <- Sys.time()

  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }
  DatabaseConnector::assertTempEmulationSchemaSet(
    dbms = DatabaseConnector::dbms(connection),
    tempEmulationSchema = tempEmulationSchema
  )

  if (createCohortTable) {
    message("Creating cohort table")
    sql <- "
      DROP TABLE IF EXISTS @cohort_database_schema.@cohort_table;

      CREATE TABLE @cohort_database_schema.@cohort_table (
        cohort_definition_id BIGINT,
        subject_id BIGINT,
        cohort_start_date DATE,
        cohort_end_date DATE
      );
    "
    DatabaseConnector::renderTranslateExecuteSql(
      connection = connection,
      sql = sql,
      cohort_database_schema = cohortDatabaseSchema,
      cohort_table = cohortTable
    )
  }

  message("Uploading concept sets")
  conceptSets <- keeperConceptSets |>
    filter(.data$target == "Disease of interest")
  DatabaseConnector::insertTable(
    connection = connection,
    tableName = "#concept_sets",
    data = conceptSets,
    dropTableIfExists = TRUE,
    createTable = TRUE,
    tempTable = TRUE,
    camelCaseToSnakeCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )

  message("Computing concept positive predictive values")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "CreateSensCohortRatios.sql",
    packageName = "Keeper",
    dbms = DatabaseConnector::dbms(connection),
    cdm_database_schema = cdmDatabaseSchema,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)

  conceptRatios <- DatabaseConnector::renderTranslateQuerySql(
    connection = connection,
    sql = "SELECT * FROM #concept_ratios",
    snakeCaseToCamelCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )
  conceptRatios <- conceptRatios |>
    filter(.data$ppv > 0.1) |>
    select("conceptId", "conceptName", "conceptSetName")

  message("Constructing sensitive cohort")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "CreateSensitiveCohort.sql",
    packageName = "Keeper",
    dbms = DatabaseConnector::dbms(connection),
    cdm_database_schema = cdmDatabaseSchema,
    cohort_database_schema = cohortDatabaseSchema,
    cohort_table = cohortTable,
    cohort_definition_id = cohortDefinitionId,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)

  sql <- "SELECT COUNT(*) FROM @cohort_database_schema.@cohort_table WHERE cohort_definition_id = @cohort_definition_id;"
  count <- DatabaseConnector::renderTranslateQuerySql(
    connection = connection,
    sql = sql,
    cohort_database_schema = cohortDatabaseSchema,
    cohort_table = cohortTable,
    cohort_definition_id = cohortDefinitionId
  )
  sql <- "SELECT COUNT(*) FROM #doi_cohort;"
  countDoi <- DatabaseConnector::renderTranslateQuerySql(connection = connection, sql = sql)
  sql <- "SELECT COUNT(*) FROM #combi_cohort;"
  countCombi <- DatabaseConnector::renderTranslateQuerySql(connection = connection, sql = sql)

  message("Removing temp tables")
  toDelete <- c("#concept_sets", "#doi_cohort", "#combi_cohort")
  sql <- paste(sprintf("TRUNCATE TABLE %s; DROP TABLE %s;", toDelete, toDelete), collapse = "\n")
  DatabaseConnector::renderTranslateExecuteSql(
    connection = connection,
    sql = sql,
    tempEmulationSchema = tempEmulationSchema
  )

  delta <- Sys.time() - startTime
  message(paste0(
    "Generating sensitive cohort took ",
    round(delta, 1),
    " ",
    attr(delta, "units"),
    ". Cohort size is ",
    format(count[1, 1], scientific = FALSE, big.mark = ","),
    " persons, ",
    format(countDoi[1, 1], scientific = FALSE, big.mark = ","),
    " with the diagnosis, and ",
    format(countCombi[1, 1], scientific = FALSE, big.mark = ","),
    " with a combination of other markers."
  ))
  attr(conceptRatios, "count") <- count[1, 1]
  attr(conceptRatios, "countDoi") <- countDoi[1, 1]
  attr(conceptRatios, "countCombi") <- countCombi[1, 1]
  invisible(conceptRatios)
}

#' Create reference cohort table names
#' 
#' @description
#' Derives a metadata table name from the reference cohort table name in a systematic way.
#'
#' @param referenceCohortTable The name of the cohort table itself. The metadata table name will be derived from this
#'                             by appending '_metadata'.
#'
#' @returns
#' A list with `referenceCohortTable` and `referenceCohortMetadataTable`.
#'
#' @export
createReferenceCohortTableNames <- function(referenceCohortTable) {
  tableNames <- list(
    referenceCohortTable = referenceCohortTable,
    referenceCohortMetadataTable = paste0(referenceCohortTable, "_metadata")
  )
  return(tableNames)
}

#' Upload a reference cohort
#'
#' @description
#' A reference cohort is typically a large sample (e.g. 10,000 persons) of a highly-sensitive cohort (as created using 
#' [createSensitiveCohort()]), reviewed by an LLM (using [reviewCases()]).
#' 
#' The reference cohort can be used to compute operating characteristics of a cohort definition for the same phenotype
#' using [computeCohortOperatingCharacteristics()].
#'
#' @template Connection
#'
#' @template TempEmulationSchema
#'
#' @param referenceCohortDatabaseSchema  The name of the database schema where the reference
#'                                       cohort will be stored.
#' @param referenceCohortTableNames      The table names where the reference cohort and metadata will be stored. Should
#'                                       be created using [createReferenceCohortTableNames()].
#' @param referenceCohortDefinitionId    The cohort definition ID that will be used for the
#'                                       reference cohort.
#' @param createReferenceCohortTables    Create the reference cohort and metadata tables? If `TRUE` and the tables
#'                                       already exists they will first be deleted.
#' @param reviews                        A data frame containing reviews as generated by [reviewCases()].
#'
#' @returns
#' This function does not return a value. It is called for the side effect of uploading
#' the reference cohort to the database.
#'
#' @export
uploadReferenceCohort <- function(connectionDetails = NULL,
                                  connection = NULL,
                                  tempEmulationSchema = getOption("sqlRenderTempEmulationSchema"),
                                  referenceCohortDatabaseSchema,
                                  referenceCohortTableNames,
                                  referenceCohortDefinitionId,
                                  createReferenceCohortTables = FALSE,
                                  reviews) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertClass(connectionDetails, "ConnectionDetails", null.ok = TRUE, add = errorMessages)
  checkmate::assertClass(connection, "DatabaseConnectorConnection", null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(referenceCohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertList(referenceCohortTableNames, len = 2, add = errorMessages)
  checkmate::assertNames(names(referenceCohortTableNames), must.include = c(
    "referenceCohortTable",
    "referenceCohortMetadataTable"
  ), add = errorMessages)
  checkmate::assertIntegerish(referenceCohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertLogical(createReferenceCohortTables, len = 1, add = errorMessages)
  checkmate::assertDataFrame(reviews, min.rows = 1, add = errorMessages)
  checkmate::assertNames(colnames(reviews), must.include = c(
    "generatedId",
    "phenotype",
    "isCase",
    "indexDay",
    "certainty",
    "justification",
    "personId",
    "cohortStartDate",
    "cohortPrevalence",
    "model",
    "keeperVersion"
  ), add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  if (is.null(connectionDetails) && is.null(connection)) {
    stop("Must provide either connectionDetails or a connection.")
  }
  metadata <- reviews |>
    distinct(.data$phenotype, .data$cohortPrevalence, .data$model, .data$keeperVersion)
  if (nrow(metadata) > 1) {
    stop("Non-unique metadata found. Please upload one cohort at a time")
  }

  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }
  DatabaseConnector::assertTempEmulationSchemaSet(
    dbms = DatabaseConnector::dbms(connection),
    tempEmulationSchema = tempEmulationSchema
  )

  if (createReferenceCohortTables) {
    message("Creating reference cohort tables")
    sql <- "
      DROP TABLE IF EXISTS @reference_cohort_database_schema.@reference_cohort_table;
      DROP TABLE IF EXISTS @reference_cohort_database_schema.@reference_cohort_metadata_table;

      CREATE TABLE @reference_cohort_database_schema.@reference_cohort_table (
        cohort_definition_id INT,
        subject_id BIGINT,
        cohort_start_date DATE,
        is_case INT,
        certainty VARCHAR(4),
        justification VARCHAR,
        observation_period_start_date DATE,
        observation_period_end_date DATE
      );

      CREATE TABLE @reference_cohort_database_schema.@reference_cohort_metadata_table (
        cohort_definition_id INT,
        phenotype VARCHAR,
        cohort_prevalence FLOAT,
        model VARCHAR,
        keeperVersion VARCHAR
      );
    "
    DatabaseConnector::renderTranslateExecuteSql(
      connection = connection,
      sql = sql,
      reference_cohort_database_schema = referenceCohortDatabaseSchema,
      reference_cohort_table = referenceCohortTableNames$referenceCohortTable,
      reference_cohort_metadata_table = referenceCohortTableNames$referenceCohortMetadataTable
    )
  }

  message("Uploading reference cohort")
  table <- reviews |>
    select(
      "personId",
      startDate = "cohortStartDate",
      "indexDay",
      "isCase",
      "certainty",
      "justification",
      "observationPeriodStartDay",
      "observationPeriodEndDay"
    ) |>
    mutate(
      isCase = if_else(.data$isCase == "yes", 1, 0),
      indexDay = if_else(is.na(.data$indexDay), 0, .data$indexDay)
    )
  DatabaseConnector::insertTable(
    connection = connection,
    data = table,
    tableName = "#cohort_stage",
    dropTableIfExists = TRUE,
    createTable = TRUE,
    tempTable = TRUE,
    tempEmulationSchema = tempEmulationSchema,
    progressBar = TRUE,
    camelCaseToSnakeCase = TRUE
  )
  DatabaseConnector::insertTable(
    connection = connection,
    data = metadata,
    tableName = "#metadata_stage",
    dropTableIfExists = TRUE,
    createTable = TRUE,
    tempTable = TRUE,
    tempEmulationSchema = tempEmulationSchema,
    progressBar = FALSE,
    camelCaseToSnakeCase = TRUE
  )
  sql <- "
    DELETE FROM @reference_cohort_database_schema.@reference_cohort_table
    WHERE cohort_definition_id = @reference_cohort_definition_id;

    DELETE FROM @reference_cohort_database_schema.@reference_cohort_metadata_table
    WHERE cohort_definition_id = @reference_cohort_definition_id;

    INSERT INTO @reference_cohort_database_schema.@reference_cohort_table (
      cohort_definition_id,
      subject_id,
      cohort_start_date,
      is_case,
      certainty,
      justification,
      observation_period_start_date,
      observation_period_end_date
    )
    SELECT
      CAST(@reference_cohort_definition_id AS INT) AS cohort_definition_id,
      CAST(person_id AS BIGINT) AS subject_id,
      CASE WHEN index_day = -9999 THEN NULL ELSE DATEADD(DAY, index_day, start_date) END AS cohort_start_date,
      is_case,
      certainty,
      justification,
      DATEADD(DAY, observation_period_start_day, start_date) AS observation_period_start_date,
      DATEADD(DAY, observation_period_end_day, start_date) AS observation_period_end_date
    FROM #cohort_stage;

    INSERT INTO @reference_cohort_database_schema.@reference_cohort_metadata_table (
      cohort_definition_id,
      phenotype,
      cohort_prevalence,
      model,
      keeperVersion
    )
    SELECT
      CAST(@reference_cohort_definition_id AS INT) AS cohort_definition_id,
      phenotype,
      cohort_prevalence,
      model,
      keeper_version
    FROM #metadata_stage;

    TRUNCATE TABLE #cohort_stage;
    DROP TABLE #cohort_stage;
    TRUNCATE TABLE #metadata_stage;
    DROP TABLE #metadata_stage;
  "
  DatabaseConnector::renderTranslateExecuteSql(
    connection = connection,
    sql = sql,
    reference_cohort_database_schema = referenceCohortDatabaseSchema,
    reference_cohort_table = referenceCohortTableNames$referenceCohortTable,
    reference_cohort_metadata_table = referenceCohortTableNames$referenceCohortMetadataTable,
    reference_cohort_definition_id = referenceCohortDefinitionId,
    reportOverallTime = FALSE,
    progressBar = FALSE
  )
}

#' Compute cohort operating characteristics based on a Reference Cohort
#'
#' @description
#' Computes operating characteristics (sensitivity, specificity, positive predictive value, AUC,
#' and Cohen's kappa) of a cohort definition by comparing it against a reference cohort created from
#' LLM review of KEEPER profiles. Metrics are computed separately for high-certainty reviews, low-certainty reviews,
#' and all reviews combined.
#'
#' @template Connection
#'
#' @param cohortDatabaseSchema           The name of the database schema containing the cohort
#'                                       to evaluate.
#' @param cohortTable                    The table name containing the cohort to evaluate.
#' @param cohortDefinitionId             The cohort definition ID of the cohort to evaluate.
#' @param referenceCohortDatabaseSchema  The name of the database schema containing the reference
#'                                       cohort (as uploaded by [uploadReferenceCohort()]).
#' @param referenceCohortTableNames      The table names where the reference cohort and metadata are stored. Should
#'                                       be created using [createReferenceCohortTableNames())].
#' @param referenceCohortDefinitionId    The cohort definition ID of the reference cohort.
#' @param type                           If `type = "incident"`, phenotypes are evaluated to also get the right cohort
#'                                       start date. If `type = "prevalent"`, the evaluation only asks whether the 
#'                                       phentype correctly classified a person as case or non-case.
#' @param washoutPeriod                  The minimum required continuous observation time prior to index date for a 
#'                                       person to be included in the cohort. People with a cohort start date within
#'                                       the washout period will be removed before computing performance metrics.
#' @param stratifyByCertainty            Stratify the output by LLM certainty level? 
#'
#' @returns
#' A tibble with one row per certainty level (`"high"`, `"low"`, `"all"`) and columns for
#' true positives, false positives, true negatives, false negatives, sensitivity, specificity,
#' PPV (each with lower and upper confidence bounds), AUC, kappa, disease prevalence and certainty.
#' 
#' Specificity and prevalence are computed both within the reference cohort, and, based on the prevalence of the highly-
#' sensitive cohort, also in the overall population.
#'
#' @export
computeCohortOperatingCharacteristics <- function(
  connectionDetails = NULL,
  connection = NULL,
  cohortDatabaseSchema,
  cohortTable,
  cohortDefinitionId,
  referenceCohortDatabaseSchema,
  referenceCohortTableNames,
  referenceCohortDefinitionId,
  type = "incident",
  washoutPeriod = 365,
  stratifyByCertainty = FALSE
) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertClass(connectionDetails, "ConnectionDetails", null.ok = TRUE, add = errorMessages)
  checkmate::assertClass(connection, "DatabaseConnectorConnection", null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(cohortTable, len = 1, add = errorMessages)
  checkmate::assertIntegerish(cohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertCharacter(referenceCohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertList(referenceCohortTableNames, len = 2, add = errorMessages)
  checkmate::assertNames(names(referenceCohortTableNames), must.include = c(
    "referenceCohortTable",
    "referenceCohortMetadataTable"
  ), add = errorMessages)
  checkmate::assertIntegerish(referenceCohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertCharacter(type, len = 1, add = errorMessages)
  checkmate::assertChoice(type, choices = c("incident", "prevalent"), add = errorMessages)
  checkmate::assertIntegerish(washoutPeriod, len = 1, add = errorMessages)
  checkmate::assertLogical(stratifyByCertainty, len = 1, add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  if (is.null(connectionDetails) && is.null(connection)) {
    stop("Must provide either connectionDetails or a connection.")
  }
  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "ComputeCohortConfusion.sql",
    packageName = "Keeper",
    reference_cohort_database_schema = referenceCohortDatabaseSchema,
    reference_cohort_table = referenceCohortTableNames$referenceCohortTable,
    reference_cohort_definition_id = referenceCohortDefinitionId,
    cohort_database_schema = cohortDatabaseSchema,
    cohort_table = cohortTable,
    cohort_definition_id = cohortDefinitionId,
    type = type,
    washout_period = washoutPeriod
  )
  confusionCounts <- DatabaseConnector::querySql(
    connection = connection,
    sql = sql,
    snakeCaseToCamelCase = TRUE
  )
  sql <- "
    SELECT certainty,
      SUM(is_case) AS cases,
      COUNT(*) - SUM(is_case) AS non_cases
    FROM @reference_cohort_database_schema.@reference_cohort_table
    WHERE cohort_definition_id = @reference_cohort_definition_id
    GROUP BY certainty;
  "
  caseCounts <- DatabaseConnector::renderTranslateQuerySql(
    connection = connection,
    sql = sql,
    reference_cohort_database_schema = referenceCohortDatabaseSchema,
    reference_cohort_table = referenceCohortTableNames$referenceCohortTable,
    reference_cohort_definition_id = referenceCohortDefinitionId,
    snakeCaseToCamelCase = TRUE
  )  
  counts <- confusionCounts |>
    inner_join(caseCounts, by = join_by("certainty"))
  sql <- "
    SELECT *
    FROM @reference_cohort_database_schema.@reference_cohort_metadata_table
    WHERE cohort_definition_id = @reference_cohort_definition_id;
  "
  metadata <- DatabaseConnector::renderTranslateQuerySql(
    connection = connection,
    sql = sql,
    reference_cohort_database_schema = referenceCohortDatabaseSchema,
    reference_cohort_metadata_table = referenceCohortTableNames$referenceCohortMetadataTable,
    reference_cohort_definition_id = referenceCohortDefinitionId,
    snakeCaseToCamelCase = TRUE
  )
  metrics <- tibble()
  if (stratifyByCertainty) {
    certaintyLevels <- c(counts$certainty, "all")
  } else {
    certaintyLevels <- "all"
  }
  for (certainty in certaintyLevels) {
    if (certainty == "all") {
      subset <- counts |>
        summarise(
          truePositives = sum(.data$truePositives),
          trueNegatives = sum(.data$trueNegatives),
          falsePositives = sum(.data$falsePositives),
          falseNegatives = sum(.data$falseNegatives),
          cases = sum(.data$cases),
          nonCases = sum(.data$nonCases)
        )
    } else {
      subset <- counts |>
        filter(.data$certainty == !!certainty)
    }
    subsetMetrics <- computePerformanceMetrics(
      tp = subset$truePositives,
      tn = subset$trueNegatives,
      fp = subset$falsePositives,
      fn = subset$falseNegatives,
      cases = subset$cases,
      nonCases = subset$nonCases,
      cohortPrevalence = metadata$cohortPrevalence
    ) |>
      mutate(certainty = !!certainty) |>
      relocate("certainty")
    metrics <- bind_rows(metrics, subsetMetrics)
  }
  return(metrics)
}

computePerformanceMetrics <- function(tp, tn, fp, fn, cases, nonCases, cohortPrevalence) {
  safeBinomTest <- function(successes, trials) {
    if (trials == 0) {
      return(list(estimate = NA_real_, conf.int = c(NA_real_, NA_real_)))
    }
    binom.test(successes, trials)
  }

  safeDivide <- function(numerator, denominator) {
    if (denominator == 0) {
      return(NA_real_)
    }
    numerator / denominator
  }

  sens <- safeBinomTest(tp, tp + fn)
  spec <- safeBinomTest(tn, tn + fp)
  specOverall <- safeBinomTest(round(tn / cohortPrevalence), round(tn / cohortPrevalence) + fp)
  pospv <- safeBinomTest(tp, tp + fp)
  n <- tp + tn + fp + fn
  prev <- as.numeric(cases) / (cases + nonCases)
  prevOverall <- as.numeric(cases) / ((cases + nonCases) / cohortPrevalence)
  observedAgreement <- safeDivide(tp + tn, n)

  pPosRater1 <- safeDivide(tp + fn, n)
  pNegRater1 <- safeDivide(tn + fp, n)
  pPosRater2 <- safeDivide(tp + fp, n)
  pNegRater2 <- safeDivide(tn + fn, n)
  expectedAgreement <- (pPosRater1 * pPosRater2) + (pNegRater1 * pNegRater2)

  kappa <- safeDivide(observedAgreement - expectedAgreement, 1 - expectedAgreement)

  metrics <- tibble(
    tp = tp,
    fp = fp,
    tn = tn,
    fn = fn,
    sensitivity = sens$estimate,
    sensitivityLb = sens$conf.int[1],
    sensitivityUb = sens$conf.int[2],
    specificity = spec$estimate,
    specificityLb = spec$conf.int[1],
    specificityUb = spec$conf.int[2],
    specificityOverall = specOverall$estimate,
    specificityOverallLb = specOverall$conf.int[1],
    specificityOverallUb = specOverall$conf.int[2],
    ppv = pospv$estimate,
    ppvLb = pospv$conf.int[1],
    ppvUb = pospv$conf.int[2],
    auc = (sens$estimate + spec$estimate) / 2,
    kappa = kappa,
    prevalence = prev,
    prevalenceOverall = prevOverall
  )
  return(metrics)
}
