# Copyright 2026 Observational Health Data Sciences and Informatics
#
# This file is part of Keeper
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create a sensitive cohort
#'
#' @description
#' Creates a cohort that is highly sensitive. Nobody outside the cohort is expected to have the disease. As a
#' consequence, specificity inside the cohort is likely low.
#'
#' This cohort can be used to determine the sensitivity of a cohort definition.
#' 
#' The cohort is constructed by combining two sets:
#' 
#' 1. Anybody who has one of the concepts of the disease of interest.
#'
#' @template Connection
#'
#' @template CdmDatabaseSchema
#'
#' @template TempEmulationSchema
#'
#' @param cohortDatabaseSchema       The name of the database schema that is the location where the
#'                                   cohort will be stored.
#' @param cohortTable                The table name where the cohort will be stored.
#' @param createCohortTable          Create the cohort table. If `TRUE` and the table already exists it will first be
#'                                   deleted.
#' @param cohortDefinitionId         The cohort definition ID that will be used for the cohort.
#' @param keeperConceptSets          A data frame with Keeper concept sets as generated by
#'                                   [generateKeeperConceptSets()].
#'
#' @returns
#' This function is primarily executed for instantiating the cohort in the cohort table. It does return a data frame
#' listing the concepts that were used to create the cohort.
#'
#' @export
createSensitiveCohort <- function(connectionDetails = NULL,
                                  connection = NULL,
                                  cdmDatabaseSchema,
                                  tempEmulationSchema = getOption("sqlRenderTempEmulationSchema"),
                                  cohortDatabaseSchema,
                                  cohortTable,
                                  createCohortTable = FALSE,
                                  cohortDefinitionId,
                                  keeperConceptSets) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertClass(connectionDetails, "ConnectionDetails", null.ok = TRUE, add = errorMessages)
  checkmate::assertClass(connection, "DatabaseConnectorConnection", null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cdmDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(tempEmulationSchema, len = 1, null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(cohortTable, len = 1, add = errorMessages)
  checkmate::assertLogical(createCohortTable, len = 1, add = errorMessages)
  checkmate::assertIntegerish(cohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertDataFrame(keeperConceptSets, min.rows = 1, add = errorMessages)
  checkmate::assertNames(colnames(keeperConceptSets), must.include = c(
    "conceptId",
    "conceptName",
    "vocabularyId",
    "conceptSetName",
    "target"
  ), add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  if (is.null(connectionDetails) && is.null(connection)) {
    stop("Must provide either connectionDetails or a connection.")
  }
  
  startTime <- Sys.time()
  
  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }
  DatabaseConnector::assertTempEmulationSchemaSet(
    dbms = DatabaseConnector::dbms(connection),
    tempEmulationSchema = tempEmulationSchema
  )
  
  if (createCohortTable) {
    message("Creating cohort table")
    sql <- "
      DROP TABLE IF EXISTS @cohort_database_schema.@cohort_table;

      CREATE TABLE @cohort_database_schema.@cohort_table (
        cohort_definition_id BIGINT,
        subject_id BIGINT,
        cohort_start_date DATE,
        cohort_end_date DATE
      );
    "
    DatabaseConnector::renderTranslateExecuteSql(
      connection = connection,
      sql = sql,
      cohort_database_schema = cohortDatabaseSchema,
      cohort_table = cohortTable
    )
  }
  
  message("Uploading concept sets")
  conceptSets <- keeperConceptSets |>
    filter(.data$target == "Disease of interest")
  DatabaseConnector::insertTable(
    connection = connection,
    tableName = "#concept_sets",
    data = conceptSets,
    dropTableIfExists = TRUE,
    createTable = TRUE,
    tempTable = TRUE,
    camelCaseToSnakeCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )
  
  message("Computing concept positive predictive values")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "CreateSensCohortRatios.sql",
    packageName = "Keeper",
    dbms = DatabaseConnector::dbms(connection),
    cdm_database_schema = cdmDatabaseSchema,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)
  
  conceptRatios <- DatabaseConnector::renderTranslateQuerySql(
    connection = connection,
    sql = "SELECT * FROM #concept_ratios",
    snakeCaseToCamelCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )
  conceptRatios <- conceptRatios |>
    filter(.data$ppv > 0.1) |>
    select("conceptId", "conceptName", "conceptSetName")
  
  message("Constructing sensitive cohort")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "CreateSensitiveCohort.sql",
    packageName = "Keeper",
    dbms = DatabaseConnector::dbms(connection),
    cdm_database_schema = cdmDatabaseSchema,
    cohort_database_schema = cohortDatabaseSchema,
    cohort_table = cohortTable,
    cohort_definition_id = cohortDefinitionId,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)
  
  sql <- "SELECT COUNT(*) FROM @cohort_database_schema.@cohort_table WHERE cohort_definition_id = @cohort_definition_id;"
  count <- DatabaseConnector::renderTranslateQuerySql(
    connection = connection,
    sql = sql,
    cohort_database_schema = cohortDatabaseSchema,
    cohort_table = cohortTable,
    cohort_definition_id = cohortDefinitionId
  )
  sql <- "SELECT COUNT(*) FROM #doi_cohort;"
  countDoi <- DatabaseConnector::renderTranslateQuerySql(connection = connection, sql = sql)
  sql <- "SELECT COUNT(*) FROM #combi_cohort;"
  countCombi <- DatabaseConnector::renderTranslateQuerySql(connection = connection, sql = sql)
  
  message("Removing temp tables")
  toDelete <- c("#concept_sets", "#doi_cohort", "#combi_cohort")
  sql <- paste(sprintf("TRUNCATE TABLE %s; DROP TABLE %s;", toDelete, toDelete), collapse = "\n")
  DatabaseConnector::renderTranslateExecuteSql(
    connection = connection,
    sql = sql,
    tempEmulationSchema = tempEmulationSchema
  )
  
  delta <- Sys.time() - startTime
  message(paste0(
    "Generating sensitive cohort took ",
    round(delta, 1),
    " ",
    attr(delta, "units"),
    ". Cohort size is ",
    format(count[1, 1], scientific = FALSE, big.mark = ","),
    " persons, ",
    format(countDoi[1, 1], scientific = FALSE, big.mark = ","),
    " with the diagnosis, and ",
    format(countCombi[1, 1], scientific = FALSE, big.mark = ","),
    " with a combination of other markers."
  ))
  attr(conceptRatios, "count") <- count[1, 1]
  attr(conceptRatios, "countDoi") <- countDoi[1, 1]
  attr(conceptRatios, "countCombi") <- countCombi[1, 1]
  invisible(conceptRatios)
}

#' Upload a reference cohort
#'
#' @description
#' Uploads a reference cohort based on chart reviews to a database table. The reference cohort
#' contains the reviewed persons with their case status, and can be used to evaluate the operating
#' characteristics of a cohort definition using [computeCohortOperatingCharacteristics()].
#'
#' @template Connection
#'
#' @template TempEmulationSchema
#'
#' @param referenceCohortDatabaseSchema  The name of the database schema where the reference
#'                                       cohort will be stored.
#' @param referenceCohortTable           The table name where the reference cohort will be stored.
#' @param referenceCohortDefinitionId    The cohort definition ID that will be used for the
#'                                       reference cohort.
#' @param createReferenceCohortTable     Create the reference cohort table. If `TRUE` and the table
#'                                       already exists it will first be deleted.
#' @param reviews                        A data frame containing reviews as generated by [reviewCases()].
#'
#' @returns
#' This function does not return a value. It is called for the side effect of uploading
#' the reference cohort to the database.
#'
#' @export
uploadReferenceCohort <- function(connectionDetails = NULL,
                                  connection = NULL,
                                  tempEmulationSchema = getOption("sqlRenderTempEmulationSchema"),
                                  referenceCohortDatabaseSchema,
                                  referenceCohortTable,
                                  referenceCohortDefinitionId,
                                  createReferenceCohortTable = FALSE,
                                  reviews) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertClass(connectionDetails, "ConnectionDetails", null.ok = TRUE, add = errorMessages)
  checkmate::assertClass(connection, "DatabaseConnectorConnection", null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(referenceCohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(referenceCohortTable, len = 1, add = errorMessages)
  checkmate::assertIntegerish(referenceCohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertLogical(createReferenceCohortTable, len = 1, add = errorMessages)
  checkmate::assertDataFrame(reviews, min.rows = 1, add = errorMessages)
  checkmate::assertNames(colnames(reviews), must.include = c(
    "generatedId",
    "phenotype",
    "isCase",
    "indexDay",
    "certainty",
    "justification",
    "personId",
    "cohortStartDate",
    "cdmDatabaseSchema"
  ), add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  if (is.null(connectionDetails) && is.null(connection)) {
    stop("Must provide either connectionDetails or a connection.")
  }
  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }
  DatabaseConnector::assertTempEmulationSchemaSet(
    dbms = DatabaseConnector::dbms(connection),
    tempEmulationSchema = tempEmulationSchema
  )
  
  table <- reviews |>
    select("personId",
           "cohortStartDate",
           "indexDay",
           "isCase",
           "phenotype",
           "certainty",
           "justification",
    ) |>
    mutate(isCase = if_else(.data$isCase == "yes", 1, 0),
           indexDay = if_else(is.na(.data$indexDay), 0, (.data$indexDay)))
  
  if (createReferenceCohortTable) {
    message("Creating reference cohort table")
    sql <- "
      DROP TABLE IF EXISTS @reference_cohort_database_schema.@reference_cohort_table;
      
      CREATE TABLE @reference_cohort_database_schema.@reference_cohort_table (
        cohort_definition_id INT,
        subject_id BIGINT,
        cohort_start_date DATE,
        is_case INT,
        phenotype VARCHAR,
        certainty VARCHAR(4),
        justification VARCHAR
      );
    "
    DatabaseConnector::renderTranslateExecuteSql(
      connection = connection,
      sql = sql,
      reference_cohort_database_schema = referenceCohortDatabaseSchema,
      reference_cohort_table = referenceCohortTable
    )
  }
  
  message("Uploading reference cohort")
  DatabaseConnector::insertTable(
    connection = connection,
    data = table,
    tableName = "#cohort_stage",
    dropTableIfExists = TRUE,
    createTable = TRUE,
    tempTable = TRUE,
    tempEmulationSchema = tempEmulationSchema,
    progressBar = TRUE,
    camelCaseToSnakeCase = TRUE
  )
  sql <- "
    INSERT INTO @reference_cohort_database_schema.@reference_cohort_table (
      cohort_definition_id, 
      subject_id,
      cohort_start_date,
      is_case,
      phenotype,
      certainty, 
      justification
    )
    SELECT
      CAST(@reference_cohort_definition_id AS INT) AS cohort_definition_id,
      CAST(person_id AS BIGINT) AS subject_id,
      DATEADD(DAY, index_day, cohort_start_date) AS cohort_start_date,
      is_case,
      phenotype,
      certainty, 
      justification
    FROM #cohort_stage cohort_stage;
      
    TRUNCATE TABLE #cohort_stage;
    DROP TABLE #cohort_stage;
  "
  DatabaseConnector::renderTranslateExecuteSql(
    connection = connection,
    sql = sql,
    reference_cohort_database_schema = referenceCohortDatabaseSchema,
    reference_cohort_table = referenceCohortTable,
    reference_cohort_definition_id = referenceCohortDefinitionId,
    reportOverallTime = FALSE,
    progressBar = FALSE
  )
}

#' Compute cohort operating characteristics
#'
#' @description
#' Computes operating characteristics (sensitivity, specificity, positive predictive value, AUC,
#' and Cohen's kappa) of a cohort definition by comparing it against a reference cohort created from
#' chart reviews. Metrics are computed separately for high-certainty reviews, low-certainty reviews,
#' and all reviews combined.
#'
#' @template Connection
#'
#' @param cohortDatabaseSchema            The name of the database schema containing the cohort
#'                                        to evaluate.
#' @param cohortTable                     The table name containing the cohort to evaluate.
#' @param cohortDefinitionId              The cohort definition ID of the cohort to evaluate.
#' @param referenceCohortDatabaseSchema   The name of the database schema containing the reference
#'                                        cohort (as uploaded by [uploadReferenceCohort()]).
#' @param referenceCohortTable            The table name containing the reference cohort.
#' @param referenceCohortDefinitionId     The cohort definition ID of the reference cohort.
#'
#' @returns
#' A tibble with one row per certainty level (`"high"`, `"low"`, `"all"`) and columns for
#' true positives, false positives, true negatives, false negatives, sensitivity, specificity,
#' PPV (each with lower and upper confidence bounds), AUC, kappa, and certainty.
#'
#' @export
computeCohortOperatingCharacteristics <- function(
    connectionDetails = NULL,
    connection = NULL,
    cohortDatabaseSchema,
    cohortTable,
    cohortDefinitionId,
    referenceCohortDatabaseSchema,
    referenceCohortTable,
    referenceCohortDefinitionId
) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertClass(connectionDetails, "ConnectionDetails", null.ok = TRUE, add = errorMessages)
  checkmate::assertClass(connection, "DatabaseConnectorConnection", null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(cohortTable, len = 1, add = errorMessages)
  checkmate::assertIntegerish(cohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertCharacter(referenceCohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(referenceCohortTable, len = 1, add = errorMessages)
  checkmate::assertIntegerish(referenceCohortDefinitionId, len = 1, add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  if (is.null(connectionDetails) && is.null(connection)) {
    stop("Must provide either connectionDetails or a connection.")
  }
  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "ComputeCohortConfusion.sql",
    packageName = "Keeper",
    reference_cohort_database_schema = referenceCohortDatabaseSchema,
    reference_cohort_table = referenceCohortTable,
    reference_cohort_definition_id = referenceCohortDefinitionId,
    cohort_database_schema = cohortDatabaseSchema,
    cohort_table = cohortTable,
    cohort_definition_id = cohortDefinitionId
  )
  confusionCounts <- DatabaseConnector::querySql(
    connection = connection,
    sql = sql,
    snakeCaseToCamelCase = TRUE
  )
  metrics <- tibble()
  for (certainty in c("high", "low", "all")) {
    if (certainty == "all") {
      subset <- confusionCounts |>
        summarise(truePositives = sum(.data$truePositives),
                  trueNegatives = sum(.data$trueNegatives),
                  falsePositives = sum(.data$falsePositives),
                  falseNegatives = sum(.data$falseNegatives))
    } else {
      subset <- confusionCounts |>
        filter(.data$certainty == !!certainty)
    }
    subsetMetrics <- computePerformanceMetrics(
      tp = subset$truePositives,
      tn = subset$trueNegatives,
      fp = subset$falsePositives,
      fn = subset$falseNegatives
    ) |>
      mutate(certainty = !!certainty)
    metrics <- bind_rows(metrics, subsetMetrics)
  }
}

computePerformanceMetrics <- function(tp, tn, fp, fn) {

  safeBinomTest <- function(successes, trials) {
    if (trials == 0) {
      return(list(estimate = NA_real_, conf.int = c(NA_real_, NA_real_)))
    }
    binom.test(successes, trials)
  }

  safeDivide <- function(numerator, denominator) {
    if (denominator == 0) {
      return(NA_real_)
    }
    numerator / denominator
  }

  sensitivity <- safeBinomTest(tp, tp + fn)
  specificity <- safeBinomTest(tn, tn + fp)
  ppv <- safeBinomTest(tp, tp + fp)

  n <- tp + tn + fp + fn
  observedAgreement <- safeDivide(tp + tn, n)

  pPosRater1 <- safeDivide(tp + fn, n)
  pNegRater1 <- safeDivide(tn + fp, n)
  pPosRater2 <- safeDivide(tp + fp, n)
  pNegRater2 <- safeDivide(tn + fn, n)
  expectedAgreement <- (pPosRater1 * pPosRater2) + (pNegRater1 * pNegRater2)

  kappa <- safeDivide(observedAgreement - expectedAgreement, 1 - expectedAgreement)

  tibble(
    tp = tp,
    fp = fp,
    tn = tn,
    fn = fn,
    sensitivity = sensitivity$estimate,
    sensitivityLb = sensitivity$conf.int[1],
    sensitivityUb = sensitivity$conf.int[2],
    specificity = specificity$estimate,
    specificityLb = specificity$conf.int[1],
    specificityUb = specificity$conf.int[2],
    ppv = ppv$estimate,
    ppvLb = ppv$conf.int[1],
    ppvUb = ppv$conf.int[2],
    auc = (sensitivity$estimate + specificity$estimate) / 2,
    kappa = kappa
  )
}

