# Copyright 2026 Observational Health Data Sciences and Informatics
#
# This file is part of Keeper
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create a sensitive cohort
#'
#' @description
#' Creates a cohort that is highly sensitive. Nobody outside the cohort is expected to have the disease. As a
#' consequence, specificity inside the cohort is likely low.
#'
#' This cohort can be used to determine the sensitivity of a cohort definition.
#'
#' @template Connection
#'
#' @template CdmDatabaseSchema
#'
#' @template TempEmulationSchema
#'
#' @param cohortDatabaseSchema       The name of the database schema that is the location where the
#'                                   cohort will be stored.
#' @param cohortTable                The table name where the cohort will be stored.
#' @param createCohortTable          Create the cohort table. If `TRUE` and the table already exists it will first be
#'                                   deleted.
#' @param cohortDefinitionId         The cohort definition ID that will be used for the cohort.
#' @param keeperConceptSets          A data frame with Keeper concept sets as generated by
#'                                   [generateKeeperConceptSets()].
#'
#' @returns
#' This function is primarily executed for instantiating the cohort in the cohort table. It does return a data frame
#' listing the concepts that were used to create the cohort.
#'
#' @export
createSensitiveCohort <- function(connectionDetails = NULL,
                                  connection = NULL,
                                  cdmDatabaseSchema,
                                  tempEmulationSchema = getOption("sqlRenderTempEmulationSchema"),
                                  cohortDatabaseSchema,
                                  cohortTable,
                                  createCohortTable = FALSE,
                                  cohortDefinitionId,
                                  keeperConceptSets) {
  errorMessages <- checkmate::makeAssertCollection()
  checkmate::assertClass(connectionDetails, "ConnectionDetails", null.ok = TRUE, add = errorMessages)
  checkmate::assertClass(connection, "DatabaseConnectorConnection", null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cdmDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(tempEmulationSchema, len = 1, null.ok = TRUE, add = errorMessages)
  checkmate::assertCharacter(cohortDatabaseSchema, len = 1, add = errorMessages)
  checkmate::assertCharacter(cohortTable, len = 1, add = errorMessages)
  checkmate::assertLogical(createCohortTable, len = 1, add = errorMessages)
  checkmate::assertIntegerish(cohortDefinitionId, len = 1, add = errorMessages)
  checkmate::assertDataFrame(keeperConceptSets, min.rows = 1, add = errorMessages)
  checkmate::assertNames(colnames(keeperConceptSets), must.include = c(
    "conceptId",
    "conceptName",
    "vocabularyId",
    "conceptSetName",
    "target"
  ), add = errorMessages)
  checkmate::reportAssertions(errorMessages)
  if (is.null(connectionDetails) && is.null(connection)) {
    stop("Must provide either connectionDetails or a connection.")
  }

  startTime <- Sys.time()

  if (is.null(connection)) {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
  }
  DatabaseConnector::assertTempEmulationSchemaSet(
    dbms = DatabaseConnector::dbms(connection),
    tempEmulationSchema = tempEmulationSchema
  )

  if (createCohortTable) {
    message("Creating cohort table")
    sql <- "
      DROP TABLE IF EXISTS @cohort_database_schema.@cohort_table;

      CREATE TABLE @cohort_database_schema.@cohort_table (
        cohort_definition_id BIGINT,
        subject_id BIGINT,
        cohort_start_date DATE,
        cohort_end_date DATE
      );
    "
    DatabaseConnector::renderTranslateExecuteSql(
      connection = connection,
      sql = sql,
      cohort_database_schema = cohortDatabaseSchema,
      cohort_table = cohortTable
    )
  }

  message("Uploading concept sets")
  conceptSets <- keeperConceptSets |>
    filter(.data$target == "Disease of interest")
  DatabaseConnector::insertTable(
    connection = connection,
    tableName = "#concept_sets",
    data = conceptSets,
    dropTableIfExists = TRUE,
    createTable = TRUE,
    tempTable = TRUE,
    camelCaseToSnakeCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )

  message("Computing concept positive predictive values")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "CreateSensCohortRatios.sql",
    packageName = "Keeper",
    dbms = DatabaseConnector::dbms(connection),
    cdm_database_schema = cdmDatabaseSchema,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)

  conceptRatios <- DatabaseConnector::renderTranslateQuerySql(
    connection = connection,
    sql = "SELECT * FROM #concept_ratios",
    snakeCaseToCamelCase = TRUE,
    tempEmulationSchema = tempEmulationSchema
  )
  conceptRatios <- conceptRatios |>
    filter(.data$ppv > 0.1) |>
    select("conceptId", "conceptName", "conceptSetName")

  message("Constructing sensitive cohort")
  sql <- SqlRender::loadRenderTranslateSql(
    sqlFilename = "CreateSensitiveCohort.sql",
    packageName = "Keeper",
    dbms = DatabaseConnector::dbms(connection),
    cdm_database_schema = cdmDatabaseSchema,
    cohort_database_schema = cohortDatabaseSchema,
    cohort_table = cohortTable,
    cohort_definition_id = cohortDefinitionId,
    tempEmulationSchema = tempEmulationSchema
  )
  DatabaseConnector::executeSql(connection = connection, sql = sql)

  sql <- "SELECT COUNT(*) FROM @cohort_database_schema.@cohort_table WHERE cohort_definition_id = @cohort_definition_id;"
  count <- DatabaseConnector::renderTranslateQuerySql(
    connection = connection,
    sql = sql,
    cohort_database_schema = cohortDatabaseSchema,
    cohort_table = cohortTable,
    cohort_definition_id = cohortDefinitionId
  )
  sql <- "SELECT COUNT(*) FROM #doi_cohort;"
  countDoi <- DatabaseConnector::renderTranslateQuerySql(connection = connection, sql = sql)
  sql <- "SELECT COUNT(*) FROM #combi_cohort;"
  countCombi <- DatabaseConnector::renderTranslateQuerySql(connection = connection, sql = sql)

  message("Removing temp tables")
  toDelete <- c("#concept_sets", "#doi_cohort", "#combi_cohort")
  sql <- paste(sprintf("TRUNCATE TABLE %s; DROP TABLE %s;", toDelete, toDelete), collapse = "\n")
  DatabaseConnector::renderTranslateExecuteSql(
    connection = connection,
    sql = sql,
    tempEmulationSchema = tempEmulationSchema
  )

  delta <- Sys.time() - startTime
  message(paste0(
    "Generating sensitive cohort took ",
    round(delta, 1),
    " ",
    attr(delta, "units"),
    ". Cohort size is ",
    format(count[1, 1], scientific = FALSE, big.mark = ","),
    " persons, ",
    format(countDoi[1, 1], scientific = FALSE, big.mark = ","),
    " with the diagnosis, and ",
    format(countCombi[1, 1], scientific = FALSE, big.mark = ","),
    " with a combination of other markers."
  ))
  attr(conceptRatios, "count") <- count[1, 1]
  attr(conceptRatios, "countDoi") <- countDoi[1, 1]
  attr(conceptRatios, "countCombi") <- countCombi[1, 1]
  invisible(conceptRatios)
}
